#############################################################################
# Makefile for building: ST_Test
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  ST_Test.pro
# Template: app
# Command: /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -o Makefile ST_Test.pro CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = aarch64-poky-linux-gcc
CXX           = aarch64-poky-linux-g++
DEFINES       = -DLAW_RAM -DQT_QML_DEBUG
CFLAGS        = -pipe --sysroot=/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot=/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux -std=c++11 -pthread -libi2c -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iplatform -Ivl53L5CX-driver/inc -Ivl6180x-driver/inc -I /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/lib/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/include -I /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include -I /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/7.3.0 -I/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib -I/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -install qinstall
QINSTALL_PROGRAM = /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ST_Test1.0.0
DISTDIR = /home/labuser/GitRepos/ST_Test/.tmp/ST_Test1.0.0
LINK          = aarch64-poky-linux-g++
LFLAGS        = --sysroot=/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux
LIBS          = $(SUBLIBS) -L:/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib 
AR            = cqs
RANLIB        = 
SED           = sed
STRIP         = aarch64-poky-linux-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c \
		platform/platform.c \
		vl53L5CX-driver/src/vl53l5cx_api.c \
		vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.c \
		vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.c \
		vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.c \
		vl6180x-driver/src/vl6180x_api.c \
		vl6180x-driver/src/vl6180x_platform.c \
		vl6180x-driver/src/vl6180x_i2c.c 
OBJECTS       = main.o \
		platform/platform.o \
		vl53L5CX-driver/src/vl53l5cx_api.o \
		vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.o \
		vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.o \
		vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.o \
		vl6180x-driver/src/vl6180x_api.o \
		vl6180x-driver/src/vl6180x_platform.o \
		vl6180x-driver/src/vl6180x_i2c.o
DIST          = /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qml_debug.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		ST_Test.pro platform/platform.h \
		platform/types.h \
		vl53L5CX-driver/inc/vl53l5cx_api.h \
		vl53L5CX-driver/inc/vl53l5cx_buffers.h \
		vl53L5CX-driver/inc/vl53l5cx_plugin_detection_thresholds.h \
		vl53L5CX-driver/inc/vl53l5cx_plugin_motion_indicator.h \
		vl53L5CX-driver/inc/vl53l5cx_plugin_xtalk.h \
		vl6180x-driver/inc/vl6180x_api.h \
		vl6180x-driver/inc/vl6180x_cfg.h \
		vl6180x-driver/inc/vl6180x_def.h \
		vl6180x-driver/inc/vl6180x_i2c.h \
		vl6180x-driver/inc/vl6180x_platform.h \
		vl6180x-driver/inc/vl6180x_types.h main.c \
		platform/platform.c \
		vl53L5CX-driver/src/vl53l5cx_api.c \
		vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.c \
		vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.c \
		vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.c \
		vl6180x-driver/src/vl6180x_api.c \
		vl6180x-driver/src/vl6180x_platform.c \
		vl6180x-driver/src/vl6180x_i2c.c
QMAKE_TARGET  = ST_Test
DESTDIR       = 
TARGET        = ST_Test


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ST_Test.pro /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qml_debug.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		ST_Test.pro
	$(QMAKE) -o Makefile ST_Test.pro CONFIG+=debug CONFIG+=qml_debug
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_mqtt.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_mqtt_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qml_debug.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf:
ST_Test.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ST_Test.pro CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c vl53L5CX-driver/inc/vl53l5cx_api.h \
		platform/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

platform/platform.o: platform/platform.c platform/platform.h \
		platform/types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o platform/platform.o platform/platform.c

vl53L5CX-driver/src/vl53l5cx_api.o: vl53L5CX-driver/src/vl53l5cx_api.c vl53L5CX-driver/inc/vl53l5cx_api.h \
		platform/platform.h \
		vl53L5CX-driver/inc/vl53l5cx_buffers.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl53L5CX-driver/src/vl53l5cx_api.o vl53L5CX-driver/src/vl53l5cx_api.c

vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.o: vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.c vl53L5CX-driver/inc/vl53l5cx_plugin_detection_thresholds.h \
		vl53L5CX-driver/inc/vl53l5cx_api.h \
		platform/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.o vl53L5CX-driver/src/vl53l5cx_plugin_detection_thresholds.c

vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.o: vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.c vl53L5CX-driver/inc/vl53l5cx_plugin_motion_indicator.h \
		vl53L5CX-driver/inc/vl53l5cx_api.h \
		platform/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.o vl53L5CX-driver/src/vl53l5cx_plugin_motion_indicator.c

vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.o: vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.c vl53L5CX-driver/inc/vl53l5cx_plugin_xtalk.h \
		vl53L5CX-driver/inc/vl53l5cx_api.h \
		platform/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.o vl53L5CX-driver/src/vl53l5cx_plugin_xtalk.c

vl6180x-driver/src/vl6180x_api.o: vl6180x-driver/src/vl6180x_api.c vl6180x-driver/inc/vl6180x_api.h \
		vl6180x-driver/inc/vl6180x_platform.h \
		vl6180x-driver/inc/vl6180x_def.h \
		vl6180x-driver/inc/vl6180x_cfg.h \
		vl6180x-driver/inc/vl6180x_types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl6180x-driver/src/vl6180x_api.o vl6180x-driver/src/vl6180x_api.c

vl6180x-driver/src/vl6180x_platform.o: vl6180x-driver/src/vl6180x_platform.c vl6180x-driver/inc/vl6180x_platform.h \
		vl6180x-driver/inc/vl6180x_def.h \
		vl6180x-driver/inc/vl6180x_cfg.h \
		vl6180x-driver/inc/vl6180x_types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl6180x-driver/src/vl6180x_platform.o vl6180x-driver/src/vl6180x_platform.c

vl6180x-driver/src/vl6180x_i2c.o: vl6180x-driver/src/vl6180x_i2c.c vl6180x-driver/inc/vl6180x_i2c.h \
		vl6180x-driver/inc/vl6180x_platform.h \
		vl6180x-driver/inc/vl6180x_def.h \
		vl6180x-driver/inc/vl6180x_cfg.h \
		vl6180x-driver/inc/vl6180x_types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vl6180x-driver/src/vl6180x_i2c.o vl6180x-driver/src/vl6180x_i2c.c

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/root/ || mkdir -p $(INSTALL_ROOT)/home/root/
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/root/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

